Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,43 +1,24 @@
-name: CI
-
+name: Backend Java
 on:
   workflow_dispatch
-
 jobs:
   build-java:
-
     runs-on: ubuntu-latest
-    
     steps:
-    - uses: actions/checkout@v2
-
-    - name: Set up JDK 1.8
-      uses: actions/setup-java@v1
-      with:
-        java-version: 1.8
-        
-    - name: Build with Gradle
-      run: |
-        cd project-1
-        gradle build
-
-    - name: copy file via SCP
-      uses: appleboy/scp-action@v0.1.4
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        password: ${{ secrets.PASSWORD }}
-        source: "project-1/build/libs/app-1.0.jar"
-        target: SB/jars
-        rm: true
-        strip_components: 3
-    - name: executing remote via SSH
-      uses: appleboy/ssh-action@v0.1.10
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        password: ${{ secrets.PASSWORD }}
-        script: |
-          cd SB
-          sudo docker-compose down
-          sudo docker-compose up --build -d
+      - name: Check if docker and docker-compose is installed and install if not
+        uses: appleboy/ssh-action@v0.1.10
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          password: ${{ secrets.PASSWORD }}
+          script: |
+            if ! command -v docker &> /dev/null
+            then
+               echo "Docker could not be found. Please install docker first."
+               sudo apt update
+               sudo apt install docker.io docker-compose -y
+               sudo usermod -aG docker ${USER}
+               su - ${USER}
+            else
+                echo "Docker is installed. Good to Go!"
+            fi
